name: Feature request
description: Suggest an improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
      description: Describe the problem or the use case, not only the solution.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you considered
  - type: dropdown
    id: contribute
    attributes:
      label: Would you like to work on it?
      options:
        - "No"
        - "Yes, with some guidance"
        - "Yes, I can open a pull request"
